### ISSUE TITLE
without https is not working

### ISSUE THREAD

**Issue by shafqatjan** [mastashake08/laravel-web-push#2]
can you please guide? and in firefox and chrome add exception  still not working (https cross line)

**Comment by mastashake08** [comment]
Have you generated vapid keys?

On Nov 28, 2017 3:04 AM, "shafqatjan" <notifications@github.com> wrote:

can you please guide? and in firefox and chrome add exception still not
working (https cross line)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mastashake08/laravel-web-push/issues/2>, or mute the
thread

**Comment by shafqatjan** [comment]
why is gmp extension is necessary? is is possible in shared hosting?

**Comment by mastashake08** [comment]
The dependency requires it. If you have shared hosting see if they will
allow you to enable the extension. Otherwise get a vps. I offer them really
cheap if you need one.

*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: @mastashake08

**Comment by deepak-kumar-sinha** [comment]
is this not working in local host ? Can u plzz guide ...

**Comment by mastashake08** [comment]
It works in localhost you just need to set up some flags. What browser are
you using?
